### ISSUE TITLE
Pull request

### ISSUE THREAD

**Issue by bgibb95** [madzadev/calculator#4]
Hi, thanks for building this, it's great. I have a small pull request to improve handling zero division. Could I be added as a contributor so I can push the branch?

**Comment by zuev93** [comment]
Hi,

I would prefer fork flow here.
https://docs.github.com/en/get-started/quickstart/contributing-to-projects
In short words: you can create fork and create pull request after to original repository.

Let me now if this will work for you.

Best regards, Zuev Vladimir.

**Comment by bgibb95** [comment]
Hi Zuev. No problem. This works for me. I've submitted a pull request :)
